# Information about where the book exists on the web
repository:
  url                       : https://github.com/vasiliadi/efficient_frontier_basics  # Online location of your book
  path_to_book              : /PyPortfolioOpt_Stocks.ipynb  # Optional path to your book, relative to the repository root
  branch                    : main  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com"
